export const ACCESSED = '2026-09-02'

export const SOURCES = [
  { name: 'Panama Protected Areas (SINAP) 2025', org: 'MiAmbiente, via STRI GIS Portal',
    use: 'Protection status, IUCN category, marine/terrestrial realm, legal basis, Ramsar sites',
    lic: 'Open data portal; national source of record', redis: 'Redistributable with attribution',
    url: 'https://stridata-si.opendata.arcgis.com/datasets/SI::panama-protected-areas-2025/about',
    note: '91 protected areas. Preferred over WDPA because it is the national register, carries the Gaceta legal basis for each area, and has no redistribution restriction.' },
  { name: 'Administrative boundaries 2024 (provinces, districts, corregimientos)', org: 'IGNTG / INEC, via STRI GIS Portal',
    use: 'Admin context, government destination polygons, comarca identification',
    lic: 'Open data portal', redis: 'Redistributable with attribution',
    url: 'https://stridata-si.opendata.arcgis.com/', note: '14 provinces including 4 comarcas, 82 districts, 699 corregimientos.' },
  { name: 'Panama watersheds & bathymetry', org: 'MiAmbiente / IGNTG, via STRI GIS Portal',
    use: 'Watershed units for the inland resilience proxy; shallow-shelf habitat extent',
    lic: 'Open data portal', redis: 'Redistributable with attribution',
    url: 'https://stridata-si.opendata.arcgis.com/', note: '52 national watersheds; bathymetric contours at 10, 20, 50, 100, 200 and 400 m.' },
  { name: 'Panama ecoregions & Holdridge life zones', org: 'STRI GIS Portal',
    use: 'Ecoregion and life-zone rarity within the biodiversity family',
    lic: 'Open data portal', redis: 'Redistributable with attribution',
    url: 'https://stridata-si.opendata.arcgis.com/', note: '9 ecoregions and 11 life zones intersect the grid.' },
  { name: 'OpenStreetMap (via Overpass API)', org: 'OpenStreetMap contributors',
    use: 'Accommodation, food service, attractions, viewpoints, beaches, waterfalls, peaks, dive/surf, marinas, ferries, airports, trails, road network',
    lic: 'ODbL 1.0', redis: 'Redistributable under ODbL with attribution',
    url: 'https://www.openstreetmap.org/copyright',
    note: '6,666 points of interest, 718 named trails and 24,067 road ways for Panama. Volunteered data: coverage is uneven and biased toward already-visited places.' },
  { name: 'ESA WorldCover 2021 v200', org: 'European Space Agency',
    use: 'Land-cover fractions at 10 m: tree cover, mangrove, wetland, cropland, built-up, water',
    lic: 'CC BY 4.0', redis: 'Redistributable with attribution',
    url: 'https://esa-worldcover.org/',
    note: 'Read remotely as cloud-optimised GeoTIFFs at decimated resolution; only per-hexagon aggregates are stored.' },
  { name: 'Copernicus DEM GLO-30', org: 'ESA / Airbus',
    use: 'Mean, minimum and maximum elevation; local relief; low-elevation coastal zone',
    lic: 'Free and open, with attribution', redis: 'Derived statistics redistributable',
    url: 'https://spacedata.copernicus.eu/collections/copernicus-digital-elevation-model',
    note: 'A digital surface model: values include canopy and structures, so peak elevations run slightly high.' },
  { name: 'WorldPop 2020 constrained (UN-adjusted)', org: 'WorldPop, University of Southampton',
    use: 'Population per cell; local labour pool; exposure behind coastal ecosystems',
    lic: 'CC BY 4.0', redis: 'Redistributable with attribution',
    url: 'https://www.worldpop.org/',
    note: 'National total over the grid is 4.02 million against roughly 4.3 million for 2020 — a modest undercount typical of constrained gridded estimates.' },
  { name: 'GBIF occurrence records', org: 'Global Biodiversity Information Facility',
    use: 'Vertebrate species richness and recording effort per H3 resolution-5 cell',
    lic: 'Records are CC0/CC BY/CC BY-NC depending on publisher', redis: 'Only aggregate counts stored and published here',
    url: 'https://www.gbif.org/',
    note: 'Birds, mammals, amphibians and reptiles with coordinates and no geospatial issues. Richness is capped at 1,000 species per class per cell by the faceting API.' },
  { name: 'PMTS 2025–2030 tourism master plan', org: 'Autoridad de Turismo de Panamá',
    use: 'Priority destinations, strategic objectives, destination value propositions, thematic routes',
    lic: 'Public government document', redis: 'Quoted and summarised with attribution',
    url: 'https://www.atp.gob.pa/wp-content/uploads/2026/07/PMTS-2025-2030-Final-compilado.pdf',
    note: '687-page approved plan. Destination boundaries are not published; polygons here are derived from official district units.' },
  { name: 'CARTO basemaps & Esri World Imagery', org: 'CARTO / Esri, Maxar',
    use: 'Cartographic basemaps only — no analytical role',
    lic: 'Free tiles with attribution', redis: 'Not redistributed; loaded at runtime',
    url: 'https://carto.com/basemaps/', note: 'No API key required.' },
]

export const NOT_USED = [
  { name: 'Allen Coral Atlas', why: 'Reproduction of the dataset is restricted without written consent from ASU. Reef presence here is proxied from bathymetric shelf extent, OSM-mapped reefs and marine protected-area designation. ACA should be the phase-2 upgrade for reef habitat and condition.', url: 'https://allencoralatlas.org/' },
  { name: 'Key Biodiversity Areas / Important Bird Areas', why: 'Access requires a data agreement and prohibits redistribution. GBIF-derived richness, ecoregion rarity and Ramsar status stand in for the biodiversity signal. KBA overlay is a clear phase-2 addition.', url: 'https://www.keybiodiversityareas.org/' },
  { name: 'WDPA / Protected Planet', why: 'Requires an API token and carries redistribution conditions. Panama’s own SINAP register is more current, more detailed and unrestricted.', url: 'https://www.protectedplanet.net/' },
  { name: 'World Bank ~90 m flood hazard maps', why: 'Not yet supplied. The data structure is designed so hazard rasters can be added as another zonal-statistics stage without redesigning the pipeline.', url: null },
]

export const STEPS = [
  { n: '10–12', t: 'Fetch', d: 'National layers from the STRI GIS Portal, OSM features via Overpass, and the government strategy encoded as structured data with derived destination polygons.' },
  { n: '20', t: 'Grid', d: 'H3 resolution-6 hexagons (~37 km²) covering all land plus a 30 km band measured from every coastline, so island archipelagos get real marine cells. 4,434 cells.' },
  { n: '13–16', t: 'Measure', d: 'Zonal statistics from WorldCover, Copernicus DEM and WorldPop; GBIF richness; a 500 m least-cost travel-time surface; and vector joins for protection, ecosystems, bathymetry and tourism assets.' },
  { n: '30', t: 'Indicators', d: 'Six named families built from ~25 sub-indicators, each percentile-ranked. Zone-aware weighting so marine cells are not penalised for having no forest.' },
  { n: '40', t: 'Classify', d: 'Continuous fit scores for four action types; the strongest becomes the primary recommendation and the others are retained as secondary. Development fit is damped where sensitivity is high.' },
  { n: '50–55', t: 'Cluster & narrate', d: 'Strongly-scoring contiguous cells of the same type are joined into named Opportunity Areas, and an investment narrative is composed from each area’s own measured values.' },
  { n: '60', t: 'Export', d: 'Simplified, coordinate-rounded GeoJSON and JSON for the application; full scored grid and area table as CSV.' },
]

export const LIMITS = [
  { t: 'This is not a flood-risk model', d: 'The resilience family is a spatial coincidence measure: protective ecosystems in front of low-lying people and assets, or catchment tree cover on slopes above them. No hydrodynamic or probabilistic modelling has been done and no avoided damages are estimated. Treat RES as a flag for where such analysis would be worth doing.' },
  { t: 'OpenStreetMap measures mapping, not tourism', d: 'Accommodation and service counts proxy existing tourism development, but OSM is best where visitors already go. A low count partly reflects low development and partly reflects low mapping effort. It is used as a development proxy deliberately, and should not be read as an inventory.' },
  { t: 'GBIF measures recording, not biodiversity', d: 'Occurrence density is heavily biased toward research stations such as Barro Colorado, roadsides and established birding sites. Richness is used as a weak positive signal and record density separately as a proxy for existing wildlife-watching interest. Neither is a survey.' },
  { t: 'Reef habitat is proxied, not mapped', d: 'Without a redistributable reef dataset, reef-capable habitat is inferred from shelf depth under 20 m, OSM-mapped reefs and marine protected-area designation. Reef condition is entirely unobserved.' },
  { t: 'Travel time is modelled', d: 'The friction surface uses road class and surface, tree cover and relief for off-road movement, and a uniform 20 km/h for sea travel standing in for boat access. It ignores traffic, ferry timetables, seasonal road closures and service frequency. Island access in particular is optimistic.' },
  { t: 'Government destination boundaries are derived', d: 'The master plan names destinations but publishes no boundaries. Polygons here are the smallest sets of official district units containing the named places, and are coarser than the destinations as ATP understands them.' },
  { t: 'Screening scale is 37 km²', d: 'A hexagon can contain both a resort strip and intact forest. Conclusions are about areas, not sites. Nothing here substitutes for site-level assessment.' },
  { t: 'Weights are analytical judgement', d: 'The weights combining sub-indicators into families, and families into fit scores, are reasoned but not empirically calibrated — no ground-truth dataset of "correct" tourism-nature opportunities exists for Panama. Every weight is visible in pipeline/30_indicators.py and pipeline/40_classify.py and can be changed.' },
  { t: 'No designation is recommended', d: 'Areas classified Protect / Restore are analytical candidates for further ecological, social, legal and stakeholder assessment. Nothing here constitutes a recommendation to designate or alter a protected area.' },
  { t: 'No employment is forecast', d: 'The jobs family measures whether a local labour and enterprise base exists and whether investment would advance decentralisation. It does not estimate job numbers, and the narratives deliberately name channels rather than counts.' },
]
